# .github/dependabot.yml
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Check all package.json files in the repository
    directory: "/"
    # Check the npm registry for updates daily
    schedule:
      interval: "daily"
